"""Train the PCA + MLP emulator for petitRADTRANS spectra.

Loads the training data generated by generate_training_data.py, fits a PCA
basis on the spectra, then trains a small MLP to predict PCA coefficients
from atmospheric parameters.  The loss is evaluated on the reconstructed
spectrum (not the raw PCA coefficients) so that the network learns to
reproduce line depths accurately.

Usage
-----
    python scripts/emulator/train_emulator.py \\
        --data_dir  emulators/carmenes_nir/order_23 \\
        --n_pca     50 \\
        --epochs    500 \\
        --batch     256

Output (all saved to data_dir/)
--------------------------------
    pca_mean.npy            (n_wave,)       spectral mean
    pca_components.npy      (k, n_wave)     PCA basis vectors
    param_bounds.npy        (2, n_params)   [min, max] per parameter
    mlp_weights.pt                          PyTorch MLP state dict
    training_log.json                       loss curves and metrics
"""

import argparse, json, os, sys, time
import numpy as np

# ── optional GPU ──────────────────────────────────────────────────────────────
try:
    import torch
    import torch.nn as nn
    _HAS_TORCH = True
except ImportError:
    _HAS_TORCH = False
    print("WARNING: PyTorch not found, install with 'pip install torch'")
    sys.exit(1)


# ── MLP architecture ──────────────────────────────────────────────────────────
class _MLP(nn.Module):
    def __init__(self, n_in, n_out, hidden=(256, 256, 128)):
        super().__init__()
        layers = []
        prev = n_in
        for h in hidden:
            layers += [nn.Linear(prev, h), nn.ReLU()]
            prev = h
        layers.append(nn.Linear(prev, n_out))
        self.net = nn.Sequential(*layers)

    def forward(self, x):
        return self.net(x)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--data_dir", default="emulators/carmenes_nir/order_23")
    ap.add_argument("--n_pca",    type=int,   default=50)
    ap.add_argument("--epochs",   type=int,   default=500)
    ap.add_argument("--batch",    type=int,   default=256)
    ap.add_argument("--lr",       type=float, default=1e-3)
    ap.add_argument("--patience", type=int,   default=30,
                    help="Early stopping patience (epochs)")
    args = ap.parse_args()

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}")

    # ── Load data ─────────────────────────────────────────────────────────────
    print("\nLoading training data...")
    params  = np.load(os.path.join(args.data_dir, "params_train.npy"))
    n_params = params.shape[1]

    # Support both old format (raw spectra) and new format (PCA coefficients)
    coeff_path = os.path.join(args.data_dir, "pca_coefficients.npy")
    spec_path  = os.path.join(args.data_dir, "spectra_train.npz")

    if os.path.exists(coeff_path):
        print("  Loading pre-computed PCA coefficients (new format)...")
        coeff_all      = np.load(coeff_path).astype(np.float32)
        pca_mean       = np.load(os.path.join(args.data_dir, "pca_mean.npy")).astype(np.float32)
        pca_components = np.load(os.path.join(args.data_dir, "pca_components.npy")).astype(np.float32)
        args.n_pca     = pca_components.shape[0]
        n_samples      = len(params)
        n_wave         = pca_components.shape[1]
        var_explained  = 1.0   # already computed during generation
        print(f"  {n_samples} samples, {args.n_pca} PCA components, {n_wave} wavelength points")
        pca_fitted = True
    else:
        print("  Loading raw spectra (old format)...")
        spectra   = np.load(spec_path)["spectra"]
        n_samples, n_wave = spectra.shape
        pca_fitted = False
        print(f"  {n_samples} spectra, {n_wave} wavelength points")

    # ── Normalise parameters to [0, 1] ───────────────────────────────────────
    bnd_path = os.path.join(args.data_dir, "param_bounds.npy")
    if os.path.exists(bnd_path):
        bnd   = np.load(bnd_path)
        p_min = bnd[0]; p_max = bnd[1]
    else:
        p_min = params.min(axis=0); p_max = params.max(axis=0)
    params_norm = ((params - p_min) / (p_max - p_min)).astype(np.float32)

    # ── Train / val / test split (80 / 10 / 10) ──────────────────────────────
    rng = np.random.default_rng(42)
    idx = rng.permutation(n_samples)
    n_train = int(0.8 * n_samples)
    n_val   = int(0.1 * n_samples)
    i_train = idx[:n_train]
    i_val   = idx[n_train:n_train + n_val]
    i_test  = idx[n_train + n_val:]
    print(f"  Split: {len(i_train)} train / {len(i_val)} val / {len(i_test)} test")

    # ── PCA (fit if needed, else use pre-computed) ────────────────────────────
    if not pca_fitted:
        print(f"\nFitting PCA with {args.n_pca} components on training set...")
        from sklearn.decomposition import PCA
        t0 = time.time()
        pca = PCA(n_components=args.n_pca, random_state=42)
        pca.fit(spectra[i_train].astype(np.float64))
        var_explained  = pca.explained_variance_ratio_.cumsum()[-1]
        pca_mean       = pca.mean_.astype(np.float32)
        pca_components = pca.components_.astype(np.float32)
        print(f"  Done in {time.time()-t0:.1f}s, "
              f"variance explained: {var_explained*100:.4f}%")
        def _to_pca(spec):
            return pca.transform(spec.astype(np.float64)).astype(np.float32)
        coeff_all = _to_pca(spectra)
    else:
        var_explained = float(np.load(os.path.join(args.data_dir, "metadata.json")
                              if False else coeff_path).shape[0])  # placeholder
        # Try to read from metadata
        meta_path = os.path.join(args.data_dir, "metadata.json")
        if os.path.exists(meta_path):
            import json as _json
            with open(meta_path) as _f:
                _m = _json.load(_f)
            var_explained = _m.get("variance_explained", 1.0)
        print(f"  Variance explained: {var_explained*100:.4f}%")

    coeff_train = coeff_all[i_train]
    coeff_val   = coeff_all[i_val]

    # ── PyTorch tensors ───────────────────────────────────────────────────────
    W  = torch.tensor(pca_components, device=device)   # (k, n_wave)
    mu = torch.tensor(pca_mean,       device=device)   # (n_wave,)

    X_tr = torch.tensor(params_norm[i_train], dtype=torch.float32, device=device)
    X_va = torch.tensor(params_norm[i_val],   dtype=torch.float32, device=device)
    Y_tr = torch.tensor(coeff_train,           dtype=torch.float32, device=device)
    Y_va = torch.tensor(coeff_val,             dtype=torch.float32, device=device)

    # Reconstruction targets for loss
    if not pca_fitted:
        S_tr = torch.tensor(spectra[i_train].astype(np.float32), device=device)
        S_va = torch.tensor(spectra[i_val].astype(np.float32),   device=device)
    else:
        # Reconstruct from PCA coefficients, avoids storing raw spectra
        S_tr = (torch.tensor(coeff_train, device=device) @ W + mu)
        S_va = (torch.tensor(coeff_val,   device=device) @ W + mu)

    # ── Model, optimiser, scheduler ──────────────────────────────────────────
    model = _MLP(n_in=n_params, n_out=args.n_pca,
                 hidden=(512, 512, 256, 128)).to(device)
    n_params_mlp = sum(p.numel() for p in model.parameters())
    print(f"\nMLP: {n_params_mlp:,} parameters")

    optimiser = torch.optim.Adam(model.parameters(), lr=args.lr)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimiser, T_max=args.epochs, eta_min=1e-5)

    # ── Training loop ─────────────────────────────────────────────────────────
    print(f"\nTraining for up to {args.epochs} epochs (early stopping patience={args.patience})...")
    train_losses, val_losses = [], []
    best_val   = np.inf
    best_state = None
    wait       = 0

    dataset = torch.utils.data.TensorDataset(X_tr, Y_tr, S_tr)
    loader  = torch.utils.data.DataLoader(dataset, batch_size=args.batch, shuffle=True)

    t0 = time.time()
    for epoch in range(1, args.epochs + 1):
        model.train()
        batch_losses = []
        for Xb, Yb, Sb in loader:
            optimiser.zero_grad()
            pred_coeff = model(Xb)
            # Reconstruction loss: MSE on the spectrum, not PCA coefficients
            pred_spec  = pred_coeff @ W + mu
            loss       = nn.functional.mse_loss(pred_spec, Sb)
            loss.backward()
            optimiser.step()
            batch_losses.append(loss.item())
        scheduler.step()

        train_loss = np.mean(batch_losses)

        model.eval()
        with torch.no_grad():
            val_pred  = model(X_va) @ W + mu
            val_loss  = nn.functional.mse_loss(val_pred, S_va).item()

        train_losses.append(float(train_loss))
        val_losses.append(float(val_loss))

        if epoch % 50 == 0:
            print(f"  epoch {epoch:4d}  train={train_loss:.2e}  val={val_loss:.2e}  "
                  f"lr={scheduler.get_last_lr()[0]:.1e}  "
                  f"elapsed={time.time()-t0:.0f}s")

        if val_loss < best_val:
            best_val   = val_loss
            best_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}
            # Save immediately, protects against crash during post-training eval
            torch.save(best_state, os.path.join(args.data_dir, "mlp_weights.pt"))
            wait = 0
        else:
            wait += 1
            if wait >= args.patience:
                print(f"  Early stopping at epoch {epoch} (patience={args.patience})")
                break

    # ── Restore best model and evaluate on test set ───────────────────────────
    model.load_state_dict(best_state)
    model.eval()
    model.cpu()

    X_te = torch.tensor(params_norm[i_test].astype(np.float32))
    W_cpu, mu_cpu = W.cpu(), mu.cpu()
    # Reconstruct test spectra from PCA coefficients (works for both formats)
    S_te = torch.tensor(coeff_all[i_test], dtype=torch.float32) @ W_cpu + mu_cpu
    with torch.no_grad():
        pred_te  = model(X_te) @ W_cpu + mu_cpu
    test_mse  = nn.functional.mse_loss(pred_te, S_te).item()
    test_rmse = np.sqrt(test_mse)
    print(f"\nTest RMSE: {test_rmse:.4e}")

    # CCF agreement on 5 random test samples
    from numpy.fft import fft, ifft
    def _ccf_peak(a, b):
        a = a - a.mean(); b = b - b.mean()
        na = np.linalg.norm(a); nb = np.linalg.norm(b)
        if na < 1e-12 or nb < 1e-12:
            return 0.0
        return float(np.max(np.real(ifft(fft(a) * np.conj(fft(b))))) / (na * nb))

    ccf_vals = []
    for j in range(min(20, len(i_test))):
        # Reconstruct true spectrum from PCA (works for both old and new format)
        true_spec = (S_te[j].numpy() if hasattr(S_te[j], 'numpy')
                     else S_te[j])
        pred_spec = pred_te[j].numpy()
        ccf_vals.append(_ccf_peak(true_spec, pred_spec))
    print(f"CCF agreement (20 test samples): "
          f"mean={np.mean(ccf_vals):.6f}  min={np.min(ccf_vals):.6f}")

    # ── Save ──────────────────────────────────────────────────────────────────
    np.save(os.path.join(args.data_dir, "pca_mean.npy"),       pca_mean)
    np.save(os.path.join(args.data_dir, "pca_components.npy"), pca_components)
    np.save(os.path.join(args.data_dir, "param_bounds.npy"),
            np.array([p_min, p_max]))
    torch.save(best_state,
               os.path.join(args.data_dir, "mlp_weights.pt"))

    log = {
        "n_pca":           args.n_pca,
        "n_params":        n_params,
        "n_wave":          int(n_wave),
        "mlp_hidden":      list((512, 512, 256, 128)),
        "variance_explained": float(var_explained),
        "best_val_loss":   float(best_val),
        "test_mse":        float(test_mse),
        "test_rmse":       float(test_rmse),
        "ccf_mean":        float(np.mean(ccf_vals)),
        "ccf_min":         float(np.min(ccf_vals)),
        "train_losses":    train_losses,
        "val_losses":      val_losses,
        "elapsed_s":       round(time.time() - t0, 1),
    }
    with open(os.path.join(args.data_dir, "training_log.json"), "w") as f:
        json.dump(log, f, indent=2)

    print(f"\nSaved to {args.data_dir}/")
    print(f"  pca_mean.npy, pca_components.npy, param_bounds.npy, mlp_weights.pt")
    print(f"  training_log.json")
    print(f"\nDone. Best val loss: {best_val:.4e}  CCF mean: {np.mean(ccf_vals):.6f}")


if __name__ == "__main__":
    sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "src"))
    main()
